version: '3.7'

services:
  ci-db:
    image: postgres:11.6-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=factlyin
      - POSTGRES_USER=factlyin
      - POSTGRES_PASSWORD=factlyin
    ports:
      - 5432:5432
    networks:
      - ci-net
  ci-app:
    build:
      context: .
    # command: /bin/sh -c "./db_install.sh && python /usr/src/app/manage.py runserver 0.0.0.0:8000"
    command: /bin/sh -c "python check_db.py --service-name ci-db --ip ci-db --port 5432 && bash ./db_install.sh && python /usr/src/app/manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_SECRET_KEY=secret-key-1234567890
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - 8000
    networks:
      - ci-net
    depends_on:
      - ci-db
  
  nginx:
    image: nginx:1.19.0-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: always
    depends_on:
      - ci-app
    networks:
      - ci-net
  
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - ci-app
    networks:
      - ci-net

volumes:
  pgdata:

networks:
  ci-net: